---
title: "ლიტერატურა"
author: "დავით სიჭინავა"
output: html_document

---

### თემა 1:

შესავალი. საქართველოს მდებარეობა. საზღვრები და ტერიტორიის ფორმირების ისტორიულ-გეოგრაფიული თავისებურებები. მიკრო-, მაკრო- და მეზომდებარეობა. წესწყობილება და ადმინისტრაციულ-ტერიტორიული მოწყობა. ეროვნული, ეკონომიკური, პოლიტიკური და დემოგრაფიული უსაფრთხოება

ლიტერატურა:

1. [საქ. გეოგრ. II ნაწილი. გვ. 13-26](https://www.dropbox.com/s/zng4xxamw25sdps/1_1_%E1%83%A1%E1%83%922.pdf?dl=0)
2. [საქ. გეოგრ. ინსტიტუტი. გვ. 13-22](https://www.dropbox.com/s/4cfvim1burr2eyu/1_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)
3. [სასწავლო-გეოგრ. ატლასი. გვ. 5-7](https://www.dropbox.com/s/3elfw7wo9cld199/1_3_%E1%83%90%E1%83%A2%E1%83%9A.pdf?dl=0)


### თემა 2:

საქართველოს ბუნებრივი პირობები და მისი გეოგრაფიული შეფასება. საქართველოს ბუნებრივი რესურსების სამეურნეო-ეკოლოგიური შეფასება

1. [საქ. გეოგრ. ინსტიტუტი. გვ. 22, 25-28, 30, 74-77, 78, 81-85, 87-89, 110-115, 145-148](https://www.dropbox.com/s/9pc8ajpb7wrmhbp/2_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)

### თემა 3:

საქართველოს მოსახლეობა: რიცხოვნობის დინამიკა, დემოგრაფიული პროცესების თანამედროვე ტენდენციები. მიგრაციები

1. [საქ. გეოგრ. II ნაწ. გვ. 27-37](https://www.dropbox.com/s/zbvtkc2otvxyrjp/3_1_%E1%83%A1%E1%83%922.pdf?dl=0)
2. [საქ. გეოგრ. ინსტიტუტი. გვ. 219-228](https://www.dropbox.com/s/azkn9lkd5iu0geo/3_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)
3. [საქ. სასწავლო-გეოგრ. ატლასი. გვ. 19](https://www.dropbox.com/s/uhiqa76jnx0y5w7/3_3_%E1%83%90%E1%83%A2%E1%83%9A.pdf?dl=0)


### თემა 4:

საქართველოს მოსახლეობა: სქესობრივ-ასაკობრივი, ეთნიკურ-რელიგიური და შრომითი სტრუქტურა

1. [საქ. გეოგრ. II ნაწ. გვ. 37-48](https://www.dropbox.com/s/aaebjqc8ecpthzd/4_1_%E1%83%A1%E1%83%922.pdf?dl=0)
2. [საქ. გეოგრ. ინსტიტუტი. გვ. 228-240](https://www.dropbox.com/s/szdkt3v0s8zo9k5/4_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)

### თემა 5:

საქართველოს მოსახლეობა: განსახლება, სასოფლო და საქალაქო განსახლება, ურბანიზაცია, მოსახლეობის სიმჭიდროვე

1. [საქ. გეოგრ. II ნაწ. გვ. 56-73](https://www.dropbox.com/s/20xeti69ynt89fo/5_1_%E1%83%A1%E1%83%922.pdf?dl=0)
2. [საქ. გეოგრ. ინსტიტუტი. გვ. 241-248](https://www.dropbox.com/s/jazgbf2katkn06p/5_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)

### თემა 6:

საქართველოს ეკონომიკის ზოგადი დახასიათება: განვითარება, ტენდენციები, დარგობრივი სტრუქტურა

1. [საქ. გეოგრ. II ნაწ. გვ. 74-78, 89-109](https://www.dropbox.com/s/ppa8t1baun4ttds/6_1_%E1%83%A1%E1%83%922.pdf?dl=0)
2. [საქ. გეოგრ. ინსტიტუტი. გვ. 258-264](https://www.dropbox.com/s/0medhm5ehcoqoam/6_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)

### თემა 7:

სოფლის მეურნეობა, სტრუქტურული და ორგანიზაციული ცვლილებები

1. [საქ. გეოგრ. ინსტიტუტი. გვ. 249-258](https://www.dropbox.com/s/wt51evg5m7yn5r0/7_2_%E1%83%A1%E1%83%92%E1%83%98.pdf?dl=0)

### თემა 8:

საქართველოს ტრანსპორტის გეოგრაფია

1. [საქ. გეოგრ. II ნაწ. გვ. 264-286](https://www.dropbox.com/s/fz66vb7qtp49k11/8_2_%E1%83%A1%E1%83%922.pdf?dl=0)

### თემა 9:

საქართველოს რეკრეაციული გეოგრაფია

1. [საქ. გეოგრ. II ნაწ. გვ. 264-286](https://www.dropbox.com/s/terohtu83z5j1zu/9_2_%E1%83%A1%E1%83%922.pdf?dl=0)

### თემა 10:

საქართველოს რეგიონები: კახეთი, მცხეთა-მთიანეთი

1. [საქ. გეოგრ. II ნაწ. გვ. 227-255](https://www.dropbox.com/s/dtknzcmqc94h9t5/10_2_%E1%83%A1%E1%83%922.pdf?dl=0)

### რუკები:

#### ატლასი:

[სასარგებლო წიაღისეული](https://www.dropbox.com/s/gk395iefju1axkm/%E1%83%AC%E1%83%98%E1%83%90%E1%83%A6%E1%83%98%E1%83%A1%E1%83%94%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A0%E1%83%94%E1%83%A1%E1%83%A3%E1%83%A0%E1%83%A1%E1%83%94%E1%83%91%E1%83%98.pdf?dl=0)

[რელიეფი](https://www.dropbox.com/s/chpn6s1ovqgsvnu/%E1%83%9D%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%A4%E1%83%98%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A0%E1%83%A3%E1%83%99%E1%83%90.pdf?dl=0)

[ატმოსფერული ნალექები](https://www.dropbox.com/s/lkt16bnvwnkwmky/%E1%83%90%E1%83%A2%E1%83%9B%E1%83%9D%E1%83%A1%E1%83%A4%E1%83%94%E1%83%A0%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%9C%E1%83%90%E1%83%9A%E1%83%94%E1%83%A5%E1%83%94%E1%83%91%E1%83%98.pdf?dl=0)

[კლიმატური რუკა](https://www.dropbox.com/s/yhwlhwc8poxui06/%E1%83%99%E1%83%9A%E1%83%98%E1%83%9B%E1%83%90%E1%83%A2%E1%83%A3%E1%83%A0%E1%83%98_%E1%83%A0%E1%83%A3%E1%83%99%E1%83%90.pdf?dl=0)

[ჰიდროგრაფიული ქსელი](https://www.dropbox.com/s/l0iv46oyxys955u/%E1%83%B0%E1%83%98%E1%83%93%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%A4%E1%83%98%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A5%E1%83%A1%E1%83%94%E1%83%9A%E1%83%98.pdf?dl=0)

[მეურნეობა](https://www.dropbox.com/s/l0iv46oyxys955u/%E1%83%B0%E1%83%98%E1%83%93%E1%83%A0%E1%83%9D%E1%83%92%E1%83%A0%E1%83%90%E1%83%A4%E1%83%98%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%A5%E1%83%A1%E1%83%94%E1%83%9A%E1%83%98.pdf?dl=0)

[კახეთი](https://www.dropbox.com/s/ao2i4jtfj8nysrb/%E1%83%99%E1%83%90%E1%83%AE%E1%83%94%E1%83%97%E1%83%98.pdf?dl=0)

[მცხეთა-მთიანეთი](https://www.dropbox.com/s/z5cnl7wk0fa23vo/%E1%83%9B%E1%83%AA%E1%83%AE%E1%83%94%E1%83%97%E1%83%90-%E1%83%9B%E1%83%97%E1%83%98%E1%83%90%E1%83%9C%E1%83%94%E1%83%97%E1%83%98.pdf?dl=0)



#### ცარიელი კონტურული რუკები:

[ადმინისტრაციული დაყოფა](https://www.dropbox.com/s/f016zf8sxxir2vq/%E1%83%90%E1%83%93%E1%83%9B%E1%83%98%E1%83%9C%E1%83%98%E1%83%A1%E1%83%A2%E1%83%A0%E1%83%90%E1%83%AA%E1%83%98%E1%83%A3%E1%83%9A%E1%83%98_%E1%83%93%E1%83%90%E1%83%A7%E1%83%9D%E1%83%A4%E1%83%90.pdf?dl=0)

[ჰიდროგრაფიული ქსელი](https://www.dropbox.com/s/d17ptl0ch0mm4la/river_outline_blank.pdf?dl=0)

[რელიეფი](https://www.dropbox.com/s/6ez1x35frlb8szq/%E1%83%A1%E1%83%98%E1%83%9B%E1%83%90%E1%83%A6%E1%83%9A%E1%83%94_%E1%83%96%E1%83%A6%E1%83%95%E1%83%98%E1%83%A1_%E1%83%93%E1%83%9D%E1%83%9C%E1%83%98%E1%83%93%E1%83%90%E1%83%9C.pdf?dl=0)

[რელიეფი და ჰიდროგრაფია](https://www.dropbox.com/s/6ez1x35frlb8szq/%E1%83%A1%E1%83%98%E1%83%9B%E1%83%90%E1%83%A6%E1%83%9A%E1%83%94_%E1%83%96%E1%83%A6%E1%83%95%E1%83%98%E1%83%A1_%E1%83%93%E1%83%9D%E1%83%9C%E1%83%98%E1%83%93%E1%83%90%E1%83%9C.pdf?dl=0)