---
title: "პრეზენტაციის თემები და განაწილება"
output: html_document

---
### რამდენიმე შენიშვნა პრეზენტაციის მომზადებისთვის

* თითოეული პრეზენტაცია უნდა გრძელდებოდეს მაქსიმუმ 20 წუთს და მასში მონაწილეობა ჯგუფის თითოეულმა წევრმა უნდა მიიღოს;
*  გახსოვდეთ, პრეზენტაციისას აუდიტორიას ამბავს მოუთხრობთ და ეს ისე უნდა გააკეთოთ, რომ მსმენელები დაინტერესდნენ და არ ჩამოეძინოთ. შეფასებისას გავითვალისწინებ არამარტო პრეზენტაციის შინაარსს, არამედ თქვენს უნარს, როგორ გადმოსცემთ გაწეულ სამუშაოს. გულდასაწყვეტი იქნება, თუკი საკუთარ ნაშრომის სათანადოდ წარმოდგენას ვერ მოახერხებთ.
* სემინარამდე ერთი დღით ადრე, ჯგუფის წევრები ერთმანეთს აუცილებლად შეხვდეთ და რეპეტიცია მოაწყვეთ. ეს დაგეხმარებათ როგორც დროის კონტროლში, ასევე - იმის სანახავად, რამდენად ლოგიკურია სლაიდების თანმიმდევრობა და თქვენი ტექსტი.
* პრეზენტაციისას შეგიძლიათ, გამოიყენოთ ე.წ. Presenter View. უფრო დაწვრილებით ნახეთ [ამ ბმულზე](https://support.office.com/en-us/article/What-is-Presenter-view-98f31265-9630-41a7-a3f1-9b4736928ee3)
* პრეზენტაციის სლაიდები უნდა შეესაბამებოდეს მის შინაარსს. ნუ გადატვირთავთ ზედმეტი ანიმაციით, გამოიყენეთ სადა ფონი და აღსაქმელი შრფიტები. აუცილებელია რუკების, დიაგრამების და მარტივი ცხრილების ჩართვა. რა თქმა უნდა, ვიზუალური მასალა თქვენს მიერ მოთხრობილი ამბის შესაბამისი უნდა იყოს.
* სლაიდებზე ნუ დაიტანთ დიდ ტექსტებს, მაგალითად, მთელ აბზაცს - მათ არავინ კითხულობს და აუდიტორიაზე უარყოფით შთაბეჭდილებას ახდენს.
* ბონუს-ქულით დაჯილდოვდებიან ის პრეზენტატორები, რომლებიც თავად გააკეთებენ დიაგრამებს და რუკებს, ასევე - მოიძიებენ დამატებით ინფორმაციას, რომელიც არც სახელმძღვანელოებში წერია და არც მე მომიწოდებია.
* გაითვალისწინეთ, პრეზენტაციის ფაილები **სემინარის დაწყებამდე** უნდა გამომიგზავნოთ ელ-ფოსტაზე.
* გაეცანით [ამ ბმულს](https://www.kent.ac.uk/careers/presentationskills.htm), სადაც პრეზენტაციის მომზადებასთან დაკავშირებული ბევრი საინტერესო რჩევაა.

### საორიენტაციო სტრუქტურა

გაითვალისწინეთ, რომ თქვენი თემის სპეციფიკიდან გამომდინარე, აღნიშნული სტრუქტურა შესაძლოა, შეიცვალოს, თუმცა ეცადეთ, რომ წინამდებარე თანმიმდევრობა დაიცვათ. რა თქმა უნდა, ეს არ არის მოთხოვნა, თუმცა მგონია, რომ მუშაობას უფრო გაგიადვილებთ.

* Power-Point-ის სატიტულო გვერდზე დაიტანეთ პრეზენტაციის სახელწოდება, ავტორების სახელები, ასევე მიუთითეთ თარიღი და გამოიყენეთ თსუ-ს ლოგო. ხელმძღვანელის სახელის მიწერა საჭირო არაა :)
* დასაწყისში, მოკლედ მიმოიხილეთ, რაზე იქნება პრეზენტაცია, ისაუბრეთ თქვენს მიზნებსა და ამოცანებზე.
	+ შესავალმა მსმენელის ყურადღება უნდა მიიპყროს და აუდიტორია თქვენდამი დადებითად უნდა განაწყოს;
* შეჯამების შემდეგ ისაუბრეთ, თუ რა მონაცემები გააანალიზეთ, რა ლიტერატურა მოიძიეთ და რატომ იყო საჭირო ამ მონაცემების/ლიტერატურის მოპოვება;
* ძირითად ნაწილში ისაუბრეთ თქვენი კვლევის (დიახ, ეს კვლევაა!) შესახებ, რა ტენდენციები და საინტერესო სიახლეები გამოავლინეთ;
* დასკვნით ნაწილში კიდევ ერთხელ დაუბრუნდით ძირითად შედეგებს და შეაჯამეთ მთავარი ტენდენციები


### პრეზენტაციის თემები

#### 21 აპრილი:
* საქართველოს მოსახლეობის ეთნორელიგიური და სოციალურ-ეკონომიკური სტრუქტურის ცვლილება 2002-2014 წლებში (მოსახლეობის აღწერის მიხედვით)
	+ გიუნაშვილი ვიქტორ
	+ კოსტავა ნათია
	+ ტაბატაძე ქეთო
	+ ასკურავა ნათია
	+ ნერგაძე გიორგი
	+ [პრეზენტაცია](https://www.dropbox.com/s/pdw9da32puvqm7h/%E1%83%9E%E1%83%A0%E1%83%94%E1%83%96%E1%83%94%E1%83%9C%E1%83%A2%E1%83%90%E1%83%AA%E1%83%98%E1%83%90-1.pptx?dl=0)

* საქართველოს საზღვრების ცვლილება 1918-1990 წლებში
	+ გულუა მარიამ
	+ ლაიშოვი რახმან
	+ ქარდავა ივლიანე
	+ ბოლქვაძე მარად
	+ ტატიშვილი გიორგი
	+ [პრეზენტაცია](https://www.dropbox.com/s/7n0dwn8q939u0ia/%E1%83%9E%E1%83%A0%E1%83%94%E1%83%96%E1%83%94%E1%83%9C%E1%83%A2%E1%83%90%E1%83%AA%E1%83%98%E1%83%90_%E1%83%AF%E1%83%922.pptx?dl=0)

#### 5 მაისი:	
* საერთაშორისო ტერორიზმი და საქართველო
	+ დაშნიანი ბექა
	+ ლეკიშვილი ლევან
	+ ქართველიშვილი გვანცა
	+ ბარბაქაძე გიორგი
	+ ტეფნაძე ბექა
	+ [პრეზენტაცია](https://www.dropbox.com/s/ibhzm3ggg4q2sm8/%E1%83%AF%E1%83%92%E1%83%A3%E1%83%A4%E1%83%98-3.pptx?dl=0)

* სტარტაპ-ტექნოლოგიები და საქართველოს ეკონომიკა
	+ დგებუაძე ვახტანგი
	+ ლოლაძე თეონა
	+ ქაჯაია ზურაბ
	+ გუტიძე ლუკა
	+ მამედოვი ელტუნ
	+ [პრეზენტაცია](https://www.dropbox.com/s/su70bbxug4cb4bu/%E1%83%AF%E1%83%92%E1%83%A3%E1%83%A4%E1%83%98-4.pptx?dl=0)

#### 19 მაისი:
* ევროკავშირთან თავისუფალი ვაჭრობის შეთანხმება (DCFTA) და საქართველოს სოფლის მეურნეობის გამოწვევები
	+ თავაძე ირაკლი
	+ შარტავა გიორგი
	+ წიკლაური მარიამ
	+ თინიკაშვილი დავით
	+ ჩიტაია ომარ
	+ [პრეზენტაცია](https://www.dropbox.com/s/z5cnl7wk0fa23vo/%E1%83%9B%E1%83%AA%E1%83%AE%E1%83%94%E1%83%97%E1%83%90-%E1%83%9B%E1%83%97%E1%83%98%E1%83%90%E1%83%9C%E1%83%94%E1%83%97%E1%83%98.pdf?dl=0)

* ბაქო-თბილისი-ახალქალაქი-ყარსის რკინიგზა და მისი მნიშვნელობა საქართველოსთვის
	+ დარბინიან სერგეი
	+ მარგველაშვილი გურამ
	+ ჭელიძე სოსო
	+ დოღონაძე საბა
	+ ცინცაძე ლაშა

#### 2 ივნისი:
* თბილისის ტრამვაის ისტორია და სამომავლო პერსპექტივები
	+ ბაკურაძე სალომე
	+ კაკრიაშვილი ნინო
	+ ნაჭყებია ვახტანგ
	+ ხაჟალია დავით
	+ კეპულაძე მარიამ
	+ [პრეზენტაცია](https://www.dropbox.com/s/k3vr4q7wm6a2qzc/%E1%83%A2%E1%83%A0%E1%83%90%E1%83%9B%E1%83%95%E1%83%90%E1%83%98.pptx?dl=0)

* ქალაქ ბათუმის თანამედროვე ურბანული განვითარების პრობლემები
	+ ბარამიძე ნინო
	+ კალანდაძე რომანი
	+ ონიანი შალვა
	+ ჯავახიშვილი მარიამი
	+ კვანტიძე ოთარ
	+ [პრეზენტაცია](https://www.dropbox.com/s/vx624urxk8plf0s/%E1%83%9E%E1%83%A0%E1%83%94%E1%83%96%E1%83%94%E1%83%9C%E1%83%A2%E1%83%90%E1%83%AA%E1%83%98%E1%83%90.pptx?dl=0)

#### 9 ივნისი:
* საქართველოს ახალი სამთო-სათხილამურო კურორტები
	+ ბარბაქაძე თამთა
	+ კარაპეტიან რევიკ
	+ რუსია გიორგი
	+ ჯანგირაშვილი თეონა
	+ კობალაძე სანდრო
	+ [პრეზენტაცია](https://www.dropbox.com/s/4cikc5fd9gq32zb/%E1%83%A1%E1%83%90%E1%83%A5.%E1%83%A1%E1%83%90%E1%83%96.%E1%83%92%E1%83%94%E1%83%9D.pptx?dl=0)

* მდინარე მაშავერას ხეობის ანთროპოგენური დაბინძურება

	+ კოტორეიშვილი ქრისტინე
	+ ბუსხრიკიძე ალექსანდრე
	+ კობახიძე სალომე
	+ სახოკია რამაზ
	+ ჯანიბეგაშვილი გივი
	+ მანასიან მარსელ
	+ [პრეზენტაცია](https://www.dropbox.com/s/4cikc5fd9gq32zb/%E1%83%A1%E1%83%90%E1%83%A5.%E1%83%A1%E1%83%90%E1%83%96.%E1%83%92%E1%83%94%E1%83%9D.pptx?dl=0)

#### 16 ივნისი:
* საქართველოს მოპოვებითი მრეწველობა და დასაქმებულთა შრომითი უფლებები
	+ იაკობიძე ბაქარ
	+ გვიმრაძე გიორგი
	+ კობერიძე ლუკა
	+ სოფრომაძე მირანდა
	+ მესხიშვილი ზურაბ
	+ [პრეზენტაცია](https://www.dropbox.com/s/b9iea591ulzcend/%E1%83%9B%E1%83%93%E1%83%98%E1%83%9C%E1%83%90%E1%83%A0%E1%83%94%20%20%E1%83%9B%E1%83%90%E1%83%A8%E1%83%90%E1%83%95%E1%83%94%E1%83%A0%E1%83%90.pptx?dl=0)